name: Build and push Docker image to dockerhub
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD}}
      - name: Build and Push to dockerhub
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: elaethan/docker-gyak:latest
      
